=== bjoern-hempel/pimcore-hempel-li/data/json/schema/command/version/resource.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Used for validation of resource.json JSON file.",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+(-(dev|rc)(.\\d+)?)?$"
        },
        "date": {
            "type": "string"
        },
        "license": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "driver-name": {
            "type": "string"
        },
        "environment": {
            "type": "string"
        },
        "host-name": {
            "type": "string"
        },
        "php-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "symfony-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "pimcore-version": {
            "type": "string",
            "pattern": "^v\\d+\\.\\d+\\.\\d+$"
        },
        "composer-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        }
    },
    "required": [
        "version",
        "date",
        "license",
        "authors",
        "driver-name",
        "environment",
        "php-version",
        "symfony-version",
        "pimcore-version",
        "composer-version"
    ],
    "additionalProperties": false
}

=== bjoern-hempel/pimcore-hempel-li/data/json/schema/command/version/resource.json
{
    "$schema": "resource.schema.json",
    "version": "0.1.24",
    "date": "Saturday, September 16, 2023 - 22:54:59",
    "license": "Copyright (c) 2023 Björn Hempel <bjoern@hempel.li>",
    "authors": [
        "Björn Hempel <bjoern@hempel.li>"
    ],
    "driver-name": "MySQL - unknown version",
    "environment": "Test",
    "host-name": "Local Development",
    "php-version": "8.2.8",
    "symfony-version": "6.3.4",
    "pimcore-version": "v11.0.9",
    "composer-version": "2.5.1"
}
